server:
  port: ${PORT:8090}

spring:
  application:
    name: zuul-api

zuul:
 #Service will be mapped under the /api URI
 prefix: /api/v1
 routes:
   track-service:
     path: /track-service/**
     serviceId: TRACK-SERVICE

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/